version: "3.8"

services:
    database:
        image: database
        build: ./database
        ports:
            - "3306:3306"
        volumes:
            - db-storage:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "BlepBlop123"

volumes:
    db-storage:
